---
- hosts: bbdd
  become: yes
  become_user: vagrant

  vars_files:
  - vars-importar.yml

  tasks:
    - name: "Crear base de datos"
      postgresql_db:
        state: present
        name: "{{ nombre_bd }}" #escribe el nombre de la base de datos en vars-importar.yml
      become: yes
      become_user: postgres

    - name: "Copiar script"
      copy:
        src: "{{ from }}" #escribe la ruta absoluta al archivo .sql en el nodo gestor en vars-importar.yml
        dest: "{{ to }}" #escribe la ruta absoluta al archivo .sql en el servdor en vars-importar.yml
        owner: vagrant
        group: vagrant

    - name: "Importar datos desde el SQL"
      become: true
      become_user: postgres
      shell: psql [tu-base-de-datos] < [ubicacion-del-sql] #misma base de datos que {{ nombre_bd }} y misma ruta que {{ to }}
